- hosts: localhost
  become: yes

  tasks:

    - name: Pull Docker Image
      command: docker pull pratham05/my-app

    - name: Stop all running containers
      shell: docker stop $(docker ps -q)
      ignore_errors: yes

    - name: Remove all containers
      shell: docker rm -f $(docker ps -aq)
      ignore_errors: yes

    - name: Run new container
      command: docker run -d -p 80:80 --name my-container pratham05/my-app
